package iitb.CRF;
/**
 *
 * @author Sunita Sarawagi
 *
 */ 


public interface  FeatureGeneratorNested extends FeatureGenerator {    
    /** for nestedCRF this controls the maximum number of x-s grouped together.
     the maximum number of symbols generated by a state in a single nested step.
     **/
    int maxMemory();
    void startScanFeaturesAt(DataSequence data, int prevPos, int pos);
};
