package LBJ2.infer;


/**
  * Anonymous inner classes extending this class are instantiated by the code
  * generated by the LBJ compiler when creating
  * <code>QuantifiedConstraintInvocation</code> representations.  Its lone
  * method computes the value of the constraint invocation's parameter.
  *
  * @author Nick Rizzolo
 **/
abstract public class InvocationArgumentReplacer extends ArgumentReplacer
{
  /**
    * Initializing constructor.
    *
    * @param c  The context of the corresponding quantified constraint
    *           invocation, except for quantification variables.
   **/
  public InvocationArgumentReplacer(Object[] c) { super(c); }


  /**
    * Computes the value of the constraint invocation's parameter.
    *
    * @return The value of the constraint invocation's parameter.
   **/
  abstract public Object compute();
}

