/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LBJ2_jni_GLPKHook */

#ifndef _Included_LBJ2_jni_GLPKHook
#define _Included_LBJ2_jni_GLPKHook
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LBJ2_jni_GLPKHook
 * Method:    createProblem
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_LBJ2_jni_GLPKHook_createProblem
  (JNIEnv *, jobject);

/*
 * Class:     LBJ2_jni_GLPKHook
 * Method:    deleteProblem
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_LBJ2_jni_GLPKHook_deleteProblem
  (JNIEnv *, jobject);

/*
 * Class:     LBJ2_jni_GLPKHook
 * Method:    setMaximize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_LBJ2_jni_GLPKHook_setMaximize
  (JNIEnv *, jobject);

/*
 * Class:     LBJ2_jni_GLPKHook
 * Method:    setMinimize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_LBJ2_jni_GLPKHook_setMinimize
  (JNIEnv *, jobject);

/*
 * Class:     LBJ2_jni_GLPKHook
 * Method:    numberOfVariables
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_LBJ2_jni_GLPKHook_numberOfVariables
  (JNIEnv *, jobject);

/*
 * Class:     LBJ2_jni_GLPKHook
 * Method:    numberOfConstraints
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_LBJ2_jni_GLPKHook_numberOfConstraints
  (JNIEnv *, jobject);

/*
 * Class:     LBJ2_jni_GLPKHook
 * Method:    addObjectiveCoefficient
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_LBJ2_jni_GLPKHook_addObjectiveCoefficient
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     LBJ2_jni_GLPKHook
 * Method:    addFixedConstraint
 * Signature: ([I[DD)V
 */
JNIEXPORT void JNICALL Java_LBJ2_jni_GLPKHook_addFixedConstraint
  (JNIEnv *, jobject, jintArray, jdoubleArray, jdouble);

/*
 * Class:     LBJ2_jni_GLPKHook
 * Method:    addLowerBoundedConstraint
 * Signature: ([I[DD)V
 */
JNIEXPORT void JNICALL Java_LBJ2_jni_GLPKHook_addLowerBoundedConstraint
  (JNIEnv *, jobject, jintArray, jdoubleArray, jdouble);

/*
 * Class:     LBJ2_jni_GLPKHook
 * Method:    addUpperBoundedConstraint
 * Signature: ([I[DD)V
 */
JNIEXPORT void JNICALL Java_LBJ2_jni_GLPKHook_addUpperBoundedConstraint
  (JNIEnv *, jobject, jintArray, jdoubleArray, jdouble);

/*
 * Class:     LBJ2_jni_GLPKHook
 * Method:    nativeSolve
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_LBJ2_jni_GLPKHook_nativeSolve
  (JNIEnv *, jobject);

/*
 * Class:     LBJ2_jni_GLPKHook
 * Method:    nativeObjectiveValue
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_LBJ2_jni_GLPKHook_nativeObjectiveValue
  (JNIEnv *, jobject);

/*
 * Class:     LBJ2_jni_GLPKHook
 * Method:    columnPrimalValueOf
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_LBJ2_jni_GLPKHook_columnPrimalValueOf
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
